Repository CDCgov/dibbs-ecr-viewer, pull requests merged in 2025-04, with the labels that each got.

#620 ci: add release drafter job
  .github/workflows/release-drafter.yaml
  containers/ecr-viewer/README.md
Labels: ci

#647 feat: add optional flag to return bundle from process-zip
  containers/ecr-viewer/api-documentation.md
  containers/ecr-viewer/seed-scripts/create-seed-data.py
  containers/ecr-viewer/src/app/api/process-zip/route.ts
  containers/ecr-viewer/src/app/api/process-zip/service.ts
  containers/ecr-viewer/src/app/tests/api/process-zip/route.test.ts
  containers/ecr-viewer/src/app/tests/api/process-zip/service.test.ts
Labels: feature

#653 docs: Update api-documentation.md
  containers/ecr-viewer/api-documentation.md
Labels: documentation

#645 feat: add occupational history accordion
  containers/ecr-viewer/src/app/services/evaluateFhirDataService.tsx
  containers/ecr-viewer/src/app/services/formatDateService.ts
  containers/ecr-viewer/src/app/services/formatService.ts
  containers/ecr-viewer/src/app/tests/components/EcrDocument/__snapshots__/EcrDocument.test.tsx.snap
  containers/ecr-viewer/src/app/tests/components/__snapshots__/ActiveProblems.test.tsx.snap
  containers/ecr-viewer/src/app/tests/services/__snapshots__/evaluateFhirDataServices.test.ts.snap
  containers/ecr-viewer/src/app/tests/services/ecrSummaryService.test.tsx
  containers/ecr-viewer/src/app/tests/services/evaluateFhirDataServices.test.ts
  containers/ecr-viewer/src/app/tests/services/formatDateService.test.tsx
  containers/ecr-viewer/src/app/tests/services/formatService.test.tsx
  containers/ecr-viewer/src/app/utils/evaluate/fhir-paths.ts
  containers/ecr-viewer/src/app/utils/evaluate/index.ts
  containers/ecr-viewer/src/app/view-data/components/DataDisplay.tsx
  containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx
  containers/ecr-viewer/src/app/view-data/components/ExpandCollapseAccordion.tsx
  containers/ecr-viewer/src/app/view-data/components/LabInfo.tsx
  containers/ecr-viewer/src/styles/ecr-viewer.scss
  containers/ecr-viewer/src/styles/utilities.scss
Labels: feature

#546 feat: Add Kysely-driven migrations
  .github/workflows/container-ecr-viewer.yaml
  containers/ecr-viewer/.env.sample
  containers/ecr-viewer/api-documentation.md
  containers/ecr-viewer/docker-compose.yaml
  containers/ecr-viewer/e2e/dual/auth.spec.ts
  containers/ecr-viewer/e2e/dual/ecr-viewer.spec.ts
  containers/ecr-viewer/e2e/migrations.spec.ts
  containers/ecr-viewer/environment.d.ts
  containers/ecr-viewer/integration/conditions.test.ts
  containers/ecr-viewer/integration/helpers/common.ts
  containers/ecr-viewer/integration/helpers/ddl.ts
  containers/ecr-viewer/integration/listEcrDataService.test.ts
  containers/ecr-viewer/integration/listEcrDataService/core.test.ts
  containers/ecr-viewer/integration/listEcrDataService/extended.test.ts
  containers/ecr-viewer/integration/save-fhir-data-service.test.ts
  containers/ecr-viewer/integration/saveFhirDataService/core.test.ts
  containers/ecr-viewer/integration/saveFhirDataService/extended.test.ts
  containers/ecr-viewer/integration/setup.ts
  containers/ecr-viewer/package-lock.json
  containers/ecr-viewer/package.json
  containers/ecr-viewer/seed-scripts/create-seed-data.py
  containers/ecr-viewer/seed-scripts/sql/01-init.sql
  containers/ecr-viewer/sql/core.sql
  containers/ecr-viewer/sql/entrypoint.sh
  containers/ecr-viewer/sql/extended.sql
  containers/ecr-viewer/src/app/api/migrate-db/migrate.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/common/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/common/index.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/index.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/extended/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/extended/index.ts
  containers/ecr-viewer/src/app/api/migrate-db/route.ts
  containers/ecr-viewer/src/app/api/process-zip/route.ts
  containers/ecr-viewer/src/app/api/process-zip/service.ts
  containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
  containers/ecr-viewer/src/app/api/services/database.ts
  containers/ecr-viewer/src/app/api/services/utils/db-config.ts
  containers/ecr-viewer/src/app/api/services/utils/db-metadata.ts
  containers/ecr-viewer/src/app/components/BackButton.tsx
  containers/ecr-viewer/src/app/components/ErrorPage.tsx
  containers/ecr-viewer/src/app/page.tsx
  containers/ecr-viewer/src/app/services/instrumentation.ts
  containers/ecr-viewer/src/app/services/listEcrDataService.ts
  containers/ecr-viewer/src/app/tests/HomePage.test.tsx
  containers/ecr-viewer/src/app/tests/api/process-zip/route.test.ts
  containers/ecr-viewer/src/app/tests/components/BackButton.test.tsx
  containers/ecr-viewer/src/app/tests/components/LoadingComponent.test.tsx
  containers/ecr-viewer/src/app/tests/components/SideNav.test.tsx
  containers/ecr-viewer/src/instrumentation.test.ts
  containers/ecr-viewer/src/instrumentation.ts
  containers/ecr-viewer/src/styles/common.scss
  containers/orchestration/docker-compose.yaml
  containers/orchestration/tests/integration/conftest.py
  containers/orchestration/tests/integration/test_orchestration.py
Labels: feature

#629 fix: make extended actually extend core
  containers/ecr-viewer/e2e/dual/ecr-viewer.spec.ts
  containers/ecr-viewer/integration/conditions.test.ts
  containers/ecr-viewer/integration/helpers/common.ts
  containers/ecr-viewer/integration/helpers/core.ts
  containers/ecr-viewer/integration/helpers/ddl.ts
  containers/ecr-viewer/integration/listEcrDataService/core.test.ts
  containers/ecr-viewer/integration/listEcrDataService/extended.test.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrate.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/common/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/common/index.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/extended/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
  containers/ecr-viewer/src/app/api/services/database.ts
  containers/ecr-viewer/src/app/api/services/types/common.ts
  containers/ecr-viewer/src/app/api/services/types/core.ts
  containers/ecr-viewer/src/app/api/services/types/extended.ts
  containers/ecr-viewer/src/app/data/conditions.ts
  containers/ecr-viewer/src/app/services/listEcrDataService.ts
Labels: fix

#659 refactor: spring cleaning
  containers/ecr-viewer/.eslintrc.json
  containers/ecr-viewer/integration/helpers/core.ts
  containers/ecr-viewer/integration/helpers/ddl.ts
  containers/ecr-viewer/integration/helpers/extended.ts
  containers/ecr-viewer/integration/listConditionsService.test.ts
  containers/ecr-viewer/integration/listEcrDataService/core.test.ts
  containers/ecr-viewer/integration/listEcrDataService/extended.test.ts
  containers/ecr-viewer/integration/saveFhirDataService/core.test.ts
  containers/ecr-viewer/integration/saveFhirDataService/extended.test.ts
  containers/ecr-viewer/integration/setup.ts
  containers/ecr-viewer/src/app/api/fhir-data/service.ts
  containers/ecr-viewer/src/app/api/health-check/route.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrate.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/extended/19700101000000_initial.ts
  containers/ecr-viewer/src/app/api/process-zip/service.ts
  containers/ecr-viewer/src/app/api/save-fhir-data/route.ts
  containers/ecr-viewer/src/app/api/save-fhir-data/service.ts
  containers/ecr-viewer/src/app/api/utils.ts
  containers/ecr-viewer/src/app/data/blobStorage/azureClient.ts
  containers/ecr-viewer/src/app/data/blobStorage/gcpClient.ts
  containers/ecr-viewer/src/app/data/blobStorage/s3Client.ts
  containers/ecr-viewer/src/app/data/blobStorage/utils.ts
  containers/ecr-viewer/src/app/data/metadataDb/__mocks__/database.ts
  containers/ecr-viewer/src/app/data/metadataDb/database.ts
  containers/ecr-viewer/src/app/data/metadataDb/dialects/common.ts
  containers/ecr-viewer/src/app/data/metadataDb/dialects/postgres.ts
  containers/ecr-viewer/src/app/data/metadataDb/dialects/sqlserver.ts
  containers/ecr-viewer/src/app/data/metadataDb/types/core.ts
  containers/ecr-viewer/src/app/data/metadataDb/types/extended.ts
  containers/ecr-viewer/src/app/data/metadataDb/utils/db-config.ts
  containers/ecr-viewer/src/app/data/metadataDb/utils/db-metadata.ts
  containers/ecr-viewer/src/app/page.tsx
  containers/ecr-viewer/src/app/services/instrumentation.ts
  containers/ecr-viewer/src/app/services/listConditionsService.ts
  containers/ecr-viewer/src/app/services/listEcrDataService.ts
  containers/ecr-viewer/src/app/tests/HomePage.test.tsx
  containers/ecr-viewer/src/app/tests/api/fhir-data/service.test.ts
  containers/ecr-viewer/src/app/tests/api/process-zip/route.test.ts
  containers/ecr-viewer/src/app/tests/api/process-zip/service.test.ts
  containers/ecr-viewer/src/app/tests/api/save-fhir-data/route.test.ts
  containers/ecr-viewer/src/app/tests/api/save-fhir-data/service.test.ts
  containers/ecr-viewer/src/app/tests/components/EcrTableContent.test.tsx
  containers/ecr-viewer/src/app/tests/data/blobStorage/azureClient.test.ts
  containers/ecr-viewer/src/app/tests/services/ecrSummaryService.test.tsx
  containers/ecr-viewer/src/app/tests/view-data.test.tsx
  containers/ecr-viewer/src/app/view-data/page.tsx
  containers/ecr-viewer/src/instrumentation.ts
Labels: chore

#660 feat: add user, program_area, user_program_area tables
  containers/ecr-viewer/integration/helpers/ddl.ts
  containers/ecr-viewer/integration/userProgramArea.test.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/20250425111400_user_prog.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/index.ts
  containers/ecr-viewer/src/app/data/metadataDb/types/core.ts
Labels: feature

#656 feat: make `extended` the default schema, any schema on any db
  .github/workflows/container-ecr-viewer.yaml
  containers/ecr-viewer/docker-compose.yaml
  containers/ecr-viewer/environment.d.ts
  containers/ecr-viewer/src/instrumentation.test.ts
  containers/ecr-viewer/src/instrumentation.ts
  containers/orchestration/docker-compose.yaml
Labels: feature

#665 docs: minor cleanup and re-org of env var docs
  containers/ecr-viewer/environment.d.ts
Labels: documentation

#664 feat: add conditions reference table
  containers/ecr-viewer/api-documentation.md
  containers/ecr-viewer/e2e/migrations.spec.ts
  containers/ecr-viewer/integration/conditionReference.test.ts
  containers/ecr-viewer/integration/helpers/ddl.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/20250428110000_condition_ref.ts
  containers/ecr-viewer/src/app/api/migrate-db/migrations/core/index.ts
  containers/ecr-viewer/src/app/api/migrate-db/route.ts
  containers/ecr-viewer/src/app/api/migrate-db/updateConditions.ts
  containers/ecr-viewer/src/app/api/process-zip/service.ts
  containers/ecr-viewer/src/app/data/metadataDb/types/core.ts
  containers/orchestration/app/constants.py
  containers/orchestration/app/main.py
  containers/orchestration/app/models.py
  containers/orchestration/assets/sample_list_conditions_response.json
  containers/orchestration/tests/integration/conftest.py
  containers/trigger-code-reference/app/db.py
  containers/trigger-code-reference/app/main.py
  containers/trigger-code-reference/assets/RCKMS Condition Codes.csv
  containers/trigger-code-reference/assets/README.md
  containers/trigger-code-reference/assets/sample_get_conditions_responses.json
  containers/trigger-code-reference/data/README.md
  containers/trigger-code-reference/data/seed_tes_data.py
  containers/trigger-code-reference/data/tes.db
  containers/trigger-code-reference/data/tes_models.py
  containers/trigger-code-reference/tests/integration/test_trigger_code_reference.py
  containers/trigger-code-reference/tests/test_condition_endpoints.py
Labels: feature

#643 fix: eRSD Warnings
  containers/ecr-viewer/src/app/services/ecrMetadataService.ts
  containers/ecr-viewer/src/app/tests/components/EcrDocument/__snapshots__/EcrDocument.test.tsx.snap
  containers/ecr-viewer/src/app/tests/components/EcrMetadata.test.tsx
  containers/ecr-viewer/src/app/tests/components/__snapshots__/ActiveProblems.test.tsx.snap
  containers/ecr-viewer/src/app/tests/components/__snapshots__/EcrMetadata.test.tsx.snap
  containers/ecr-viewer/src/app/tests/components/__snapshots__/EcrTableContent.test.tsx.snap
  containers/ecr-viewer/src/app/tests/components/__snapshots__/Immunizations.test.tsx.snap
  containers/ecr-viewer/src/app/tests/components/__snapshots__/LabInfo.test.tsx.snap
  containers/ecr-viewer/src/app/tests/services/__snapshots__/evaluateFhirDataServices.test.ts.snap
  containers/ecr-viewer/src/app/tests/services/ecrMetadataService.test.ts
  containers/ecr-viewer/src/app/tests/services/labsService.test.tsx
  containers/ecr-viewer/src/app/utils/data-utils.tsx
  containers/ecr-viewer/src/app/utils/eicr-processing-utils.ts
  containers/ecr-viewer/src/app/utils/evaluate/fhir-paths.ts
  containers/ecr-viewer/src/app/utils/evaluate/index.ts
  containers/ecr-viewer/src/app/view-data/components/EcrDocument/accordion-items.tsx
  containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx
  containers/ingestion/tests/assets/example_eicr_with_rr_data_with_person.json
  containers/ingestion/tests/test_fhir_transport_http.py
  containers/message-parser/app/default_schemas/ecr.json
  containers/message-parser/app/default_schemas/ecr_with_metadata.json
  containers/message-parser/app/default_schemas/extended.json
  containers/trigger-code-reference/assets/sample_stamp_condition_extensions_requests.json
  containers/trigger-code-reference/assets/sample_stamp_condition_extensions_responses.json
  containers/trigger-code-reference/tests/assets/sample_ecr.json
  containers/trigger-code-reference/tests/test_utils.py
  test-data/fhir/BundleEcrMetadata.json
  test-data/fhir/BundleErsdWarningNoDetail.json
  test-data/fhir/sample_ecr.json
Labels: fix
